language: python

python:
  - '3.6'


addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
      sudo: true
      install:
        - if [ ! -d "$HOME/miniconda/bin" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && bash miniconda.sh -f -b -p $HOME/miniconda; fi
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a
        - conda create -q -n rnftools -c bioconda "python>=3" wgsim dwgsim art mason pysam samtools curesim snakemake git || true
        - source activate rnftools
        - pip install --upgrade .

    - os: osx
      before_install:
        - brew update
        - brew tap homebrew/versions
      install:
        - if [ ! -d "$HOME/miniconda/bin" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh && bash miniconda.sh -f -b -p $HOME/miniconda; fi
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a
        - conda create -q -n rnftools -c bioconda "python>=3" wgsim dwgsim art mason pysam samtools curesim snakemake git || true
        - source activate rnftools
        - pip install --upgrade .

before_script:
- git clone git://github.com/sstephenson/bats $PWD/bats
- export PATH=$PATH:$PWD/bats/bin

script:
- cd tests && bats ${CI:+--tap} ./tests_run.sh
