language: python
sudo: false
cache:
  - brew
  - apt: true
cache:
  directories:
  - $HOME/.smbl
  - $HOME/.cache/pip
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
matrix:
  include:
    - os: linux 
      sudo: true
      install:
        - if [ ! -d "$HOME/miniconda/bin" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh && bash miniconda.sh -f -b -p $HOME/miniconda; fi
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a
        - conda create -q -n rnftools -c bioconda "python>=3" wgsim dwgsim art mason pysam samtools git || true
        - source activate rnftools

    - os: osx
      before_install:
        - brew update
        - brew tap homebrew/versions
      install:
        - if [ ! -d "$HOME/miniconda/bin" ]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh && bash miniconda.sh -f -b -p $HOME/miniconda; fi
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a
        - conda create -q -n rnftools -c bioconda "python>=3" wgsim dwgsim art mason pysam samtools git || true
        - source activate rnftools

before_script:
- git clone git://github.com/sstephenson/bats $PWD/bats
- export PATH=$PATH:$PWD/bats/bin
script:
- cd tests && bats ${CI:+--tap} ./tests_run.sh
